name: 🐛 Bug Report
description: Report a bug with the baseline patterns
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us understand and fix the issue.
        
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: I'm using the latest version of this package
          required: true
        - label: I've read the documentation
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Create a Laravel project with...
        2. Add the baseline configuration...
        3. Run PHPStan with...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: phpstan-config
    attributes:
      label: PHPStan Configuration
      description: Your phpstan.neon configuration
      render: neon
      placeholder: |
        includes:
            - vendor/laravel-filament/phpstan-baseline/baselines/laravel-11.neon
        parameters:
            level: 5
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide your environment details
      value: |
        - PHP version:
        - Laravel version:
        - Filament version (if applicable):
        - PHPStan version:
        - Package version:
        - Operating System:
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Copy and paste the full error output from PHPStan
      render: shell
      placeholder: Paste the error output here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might be helpful...